apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: glyvephkr-go 
  janus-idp.io/tekton: glyvephkr-go
  backstage.io/kubernetes-id: glyvephkr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: glyvephkr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  